# Generated by Django 4.2.5 on 2023-09-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0006_sitebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebanner',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
